// Generated by gencpp from file topic_test/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TOPIC_TEST_MESSAGE_ADDTWOINTS_H
#define TOPIC_TEST_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <topic_test/AddTwoIntsRequest.h>
#include <topic_test/AddTwoIntsResponse.h>


namespace topic_test
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace topic_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::topic_test::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::topic_test::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::topic_test::AddTwoInts > {
  static const char* value()
  {
    return "topic_test/AddTwoInts";
  }

  static const char* value(const ::topic_test::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::topic_test::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::topic_test::AddTwoInts >
template<>
struct MD5Sum< ::topic_test::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::topic_test::AddTwoInts >::value();
  }
  static const char* value(const ::topic_test::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::topic_test::AddTwoIntsRequest> should match
// service_traits::DataType< ::topic_test::AddTwoInts >
template<>
struct DataType< ::topic_test::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::topic_test::AddTwoInts >::value();
  }
  static const char* value(const ::topic_test::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::topic_test::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::topic_test::AddTwoInts >
template<>
struct MD5Sum< ::topic_test::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::topic_test::AddTwoInts >::value();
  }
  static const char* value(const ::topic_test::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::topic_test::AddTwoIntsResponse> should match
// service_traits::DataType< ::topic_test::AddTwoInts >
template<>
struct DataType< ::topic_test::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::topic_test::AddTwoInts >::value();
  }
  static const char* value(const ::topic_test::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOPIC_TEST_MESSAGE_ADDTWOINTS_H
