// Generated by gencpp from file topic_test/StringMessage.msg
// DO NOT EDIT!


#ifndef TOPIC_TEST_MESSAGE_STRINGMESSAGE_H
#define TOPIC_TEST_MESSAGE_STRINGMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topic_test
{
template <class ContainerAllocator>
struct StringMessage_
{
  typedef StringMessage_<ContainerAllocator> Type;

  StringMessage_()
    : data()  {
    }
  StringMessage_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::topic_test::StringMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topic_test::StringMessage_<ContainerAllocator> const> ConstPtr;

}; // struct StringMessage_

typedef ::topic_test::StringMessage_<std::allocator<void> > StringMessage;

typedef boost::shared_ptr< ::topic_test::StringMessage > StringMessagePtr;
typedef boost::shared_ptr< ::topic_test::StringMessage const> StringMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topic_test::StringMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topic_test::StringMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topic_test::StringMessage_<ContainerAllocator1> & lhs, const ::topic_test::StringMessage_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topic_test::StringMessage_<ContainerAllocator1> & lhs, const ::topic_test::StringMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topic_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::topic_test::StringMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic_test::StringMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic_test::StringMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic_test::StringMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_test::StringMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic_test::StringMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topic_test::StringMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::topic_test::StringMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::topic_test::StringMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topic_test/StringMessage";
  }

  static const char* value(const ::topic_test::StringMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topic_test::StringMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
;
  }

  static const char* value(const ::topic_test::StringMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topic_test::StringMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topic_test::StringMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topic_test::StringMessage_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPIC_TEST_MESSAGE_STRINGMESSAGE_H
